image: Visual Studio 2019
configuration:
  - Debug
  - Release
platform:
  - x86
  - x64


build_script:
  - set PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Libraries\boost_1_71_0\lib64-msvc-14.2;C:\Libraries\boost_1_71_0\lib-msvc-14.2;%PATH%
  - mysqladmin --user=root password -pPassword12! ""
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
  - mkdir build
  - cd build
  - cmake -G Ninja -DBOOST_ROOT=C:\Libraries\boost_1_71_0 -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ..
  - cmake --build . -j

test_script:
  - ctest --output-on-failure

services:
  - mysql