language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      services:
        - mysql
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.70

#    - os: osx
#      osx_image: xcode11.3
#      sudo: true
#      compiler: clang
#      addons:
#        homebrew:
#          packages:
#            - boost
#            - mysql
#      before_install:
#        - mysql.server start
#      env:
#        - CMAKE_OPTIONS=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl


script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release $CMAKE_OPTIONS .. 
  - make -j CTEST_OUTPUT_ON_FAILURE=1 all test

