__windows_defaults: &__windows_defaults
  os: windows
  language: sh # For some reason, language cpp will start an Ubuntu machine instead
  script:
    - cmd //c 'ci\build_windows.bat'

__linux_defaults: &__linux_defaults
  os: linux
  dist: bionic
  sudo: true
  services:
    - mysql
  addons:
    apt:
      update: true
      sources:
        - sourceline: 'ppa:mhier/libboost-latest'
      packages:
        - boost1.70
  script:
    - bash -e -x ci/build_unix.sh

__osx_defaults: &__osx_defaults
  os: osx
  osx_image: xcode11.3
  sudo: true
  compiler: clang
  before_install:
    - brew update
    - brew install boost mysql
    - mysql.server start
  script:
    - bash -e -x ci/build_unix.sh

__osx_cmake_options: &__osx_cmake_options "CMAKE_OPTIONS=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"


language: cpp

matrix:
  include:
    - name: windows_msvc_x64_debug
      <<: *__windows_defaults
      env:
        - CMAKE_BUILD_TYPE=Debug
        - TARGET_ARCH=x64
    - name: windows_msvc_x64_release
      <<: *__windows_defaults
      env:
        - CMAKE_BUILD_TYPE=Release
        - TARGET_ARCH=x64
    - name: linux_gcc_x64_debug
      <<: *__linux_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Debug
    - name: linux_gcc_x64_release
      <<: *__linux_defaults
      compiler: gcc
      env:
        - CMAKE_BUILD_TYPE=Release
    - name: linux_clang_x64_debug
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Debug
    - name: linux_clang_x64_release
      <<: *__linux_defaults
      compiler: clang
      env:
        - CMAKE_BUILD_TYPE=Release
    - name: osx_clang_x64_debug
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Debug
    - name: osx_clang_x64_release
      <<: *__osx_defaults
      env:
        - *__osx_cmake_options
        - CMAKE_BUILD_TYPE=Release
