language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      services:
        - mysql
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.70
    - os: osx
      osx_image: xcode11.3
      sudo: true
      compiler: clang
      addons:
        homebrew:
          packages:
            - boost
            - mysql
            - openssl
      before_install:
        - mysql.server start


script:
  - mysql -u root < test/integration/db_setup.sql
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - make -j CTEST_OUTPUT_ON_FAILURE=1 all test

