language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:mhier/libboost-latest'
         packages:
           - boost1.70
    - os: osx
      osx_image: xcode11.3
      sudo: true
      compiler: clang
      addons:
       homebrew:
         packages:
           - boost

services:
  - mysql
  
before_install:
  - mysql -u root < test/integration/db_setup.sql

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - make -j CTEST_OUTPUT_ON_FAILURE=1 all test

